import type { Metadata } from "next";
import { Roboto , Pixelify_Sans } from '@next/font/google';
import "./globals.css";

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-roboto',
});

const pixelifySans = Pixelify_Sans({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-pixel',
});

export const metadata: Metadata = {

  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable}, ${pixelifySans.variable}`}>
        {children}
      </body>
    </html>
  );
}
